"""empty message

Revision ID: 6cbb43ec742a
Revises: 2c4749891cb6
Create Date: 2024-09-30 19:37:37.213342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbb43ec742a'
down_revision = '2c4749891cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surface_water', sa.String(), nullable=True))
        batch_op.drop_column('surface')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surface', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('surface_water')

    # ### end Alembic commands ###
